/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BookScore.Visual;

import BookScore.Banco.ControleDados.CntrlNota;
import BookScore.Banco.ControleDados.CtrlLivro;
import BookScore.Banco.ControleDados.CtrlUsuarios;
import BookScore.Model.Livro;
import BookScore.Model.Nota;
import BookScore.Model.Singleton;
import BookScore.Model.Usuarios;
import javax.swing.JOptionPane;


public class TelaCadastroLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroLivro
     */
    public TelaCadastroLivro() {
        super("BookScore - Cadastro de Livros");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonVoltarTelaInicial = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboCateg = new javax.swing.JComboBox<>();
        textFieldNomeLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textFieldNomeAutor = new javax.swing.JTextField();
        buttonCadastrarLivro = new javax.swing.JButton();
        notaLivroTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 51, 51));

        jPanel2.setBackground(new java.awt.Color(46, 79, 79));

        buttonVoltarTelaInicial.setBackground(new java.awt.Color(14, 131, 136));
        buttonVoltarTelaInicial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonVoltarTelaInicial.setForeground(new java.awt.Color(203, 228, 222));
        buttonVoltarTelaInicial.setText("Voltar");
        buttonVoltarTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarTelaInicialActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(203, 228, 222));
        jLabel3.setText("Insira o nome do Autor:");

        jComboCateg.setBackground(new java.awt.Color(203, 228, 222));
        jComboCateg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboCateg.setForeground(new java.awt.Color(44, 51, 51));
        jComboCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Categoria ", "Romance", "Ficção", "Técnico" }));

        textFieldNomeLivro.setBackground(new java.awt.Color(203, 228, 222));
        textFieldNomeLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldNomeLivro.setForeground(new java.awt.Color(44, 51, 51));

        jLabel1.setForeground(new java.awt.Color(203, 228, 222));
        jLabel1.setText("Insira o nome do Livro:");

        textFieldNomeAutor.setBackground(new java.awt.Color(203, 228, 222));
        textFieldNomeAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldNomeAutor.setForeground(new java.awt.Color(44, 51, 51));

        buttonCadastrarLivro.setBackground(new java.awt.Color(14, 131, 136));
        buttonCadastrarLivro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCadastrarLivro.setForeground(new java.awt.Color(203, 228, 222));
        buttonCadastrarLivro.setText("Cadastrar");
        buttonCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarLivroActionPerformed(evt);
            }
        });

        notaLivroTextField.setBackground(new java.awt.Color(203, 228, 222));
        notaLivroTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        notaLivroTextField.setForeground(new java.awt.Color(44, 51, 51));

        jLabel2.setForeground(new java.awt.Color(203, 228, 222));
        jLabel2.setText("Dê uma nota de 0 a 10:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(203, 228, 222));
        jLabel4.setText("Cadastro de Livro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jComboCateg, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(buttonVoltarTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addComponent(textFieldNomeLivro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textFieldNomeAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notaLivroTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(142, 142, 142))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notaLivroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltarTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarLivroActionPerformed
        String nomeLivro = textFieldNomeLivro.getText();
        String nomeAutor = textFieldNomeAutor.getText();
        String stringNota = notaLivroTextField.getText();
        int notaLivro = Integer.parseInt(stringNota);
        String tipo = jComboCateg.getSelectedItem().toString();
        
        CtrlUsuarios users = new CtrlUsuarios();
        CtrlLivro livros = new CtrlLivro();
        CntrlNota notas = new CntrlNota();
        
        if(nomeLivro != null || nomeAutor != null){
            try{
                if(!livros.existeLivro(nomeLivro)){
                    
                    if(notaLivro > 0 && notaLivro <= 10){
            
                        if (livros.novoLivro(nomeLivro, nomeAutor, tipo)) {
                    
                            JOptionPane.showMessageDialog(null,"Livro cadastrado com sucesso!");

                            int idLivro = livros.pegarIdLivro(nomeLivro);
                            int idUser = Singleton.getInstance().getIdUsuario();
   
                            if(notas.registrarNota(notaLivro,idUser, idLivro)) {
                                                                
                                 this.dispose();
                                 
                                 new TelaCadastroLivro().setVisible(true);
                            }
                            else{
                                 JOptionPane.showMessageDialog(null,"Erro ao cadastrar livro.");
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"Erro ao cadastrar livro.");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Por favor, insira uma nota de 0 a 10!", "Nota inválida", JOptionPane.ERROR_MESSAGE);
                
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Parece que o livro que você está tentando cadastrar já esta em nossos registros! \n\nTente apenas avalia-lo na 'Tela Inicial'", "Livro já cadastrado", JOptionPane.ERROR_MESSAGE);

                }    
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        else {
            JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos solicitados!", "Campos vazios", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCadastrarLivroActionPerformed

    private void buttonVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarTelaInicialActionPerformed
        TelaInicialUsuario tiUsuario = new TelaInicialUsuario();
        tiUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonVoltarTelaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarLivro;
    private javax.swing.JButton buttonVoltarTelaInicial;
    private javax.swing.JComboBox<String> jComboCateg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField notaLivroTextField;
    private javax.swing.JTextField textFieldNomeAutor;
    private javax.swing.JTextField textFieldNomeLivro;
    // End of variables declaration//GEN-END:variables
}
